### ISSUE TITLE
Slideshow

### ISSUE THREAD

**Issue by agrignard** [VCityTeam/UD-Demo-Anthropocene-GratteCiel-#2]
We need to be able to place n images (.png, .gif or even.mov) in a specific folder and give the possibility to the user to press left or right arrow to iterate like a slideshow on specific rectangle place in UD_Viz

**Comment by agrignard** [comment]
- Extended Doc @CorentinGaut with the template

1. Extended Doc avec Interface => almost done
2. Extended Doc avec un keylistener => TO DO 

- Geometry Plane @mathieuLivebardon

**Comment by agrignard** [comment]
https://github.com/VCityTeam/UD_ReAgent_ABM/blob/master/Data/Data_cc46/500x1000.png

**Comment by CorentinGaut** [comment]
With the extended doc Widget we can done this type of presentation ->
![ExtendedDocGif3](https://user-images.githubusercontent.com/32339907/150170506-449b9a71-69f8-49bb-9a95-01d1706850b3.gif)

But to develop with keyboard input we need more time

**Comment by mathieuLivebardon** [comment]
![SlideDragAndDrop](https://user-images.githubusercontent.com/34244904/150380162-2825bfdc-afed-4a72-8f5f-79647b7c7fc3.gif)
With a PlaneGeometry
Drag And Drops Pictures then you can change the texture of PlaneGeometry with ArrowLeft and ArrowRight.
You can also hide the plane.

**Comment by agrignard** [comment]
@mathieuLivebardon in the same idea as issue #1 with @corentin is it ok for you to point to the right commit? and see how we can merge it in UD_VIz?

**Comment by agrignard** [comment]
This issue can be now closed as the feature is implemented and only need to be merge in UD VIZ (see issue #8 )
