### ISSUE TITLE
3d tiler Coloring

### ISSUE THREAD

**Issue by agrignard** [VCityTeam/UD-Demo-Anthropocene-GratteCiel-#5]
- From a geojson produce a 3D tile that can be colored

**Comment by LorenzoMarnat** [comment]
Done with this [PR](https://github.com/VCityTeam/py3dtilers/pull/38) (see [Color module](https://github.com/VCityTeam/py3dtilers/tree/master/py3dtilers/Color) and [JSON config file](https://github.com/VCityTeam/py3dtilers/blob/master/py3dtilers/Color/default_config.json)).
